version: '3.8'

services: 
  app:
    build:
      context: .
    image: peraltafederico/invoices-app-front:latest
    ports:
      - $APP_PORT:$APP_PORT
    environment:
        GATSBY_API_BASE_URL: $GATSBY_API_BASE_URL