name: Deploy App

on:
  push:
    tags:
      - "*"
  
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Caching Gatsby
        id: gatsby-cache-build
        uses: actions/cache@v2
        with:
          path: |
            public
            .cache
            node_modules
          key: ${{ runner.os }}-invoices-app-${{ github.run_id }}
          restore-keys: |
            ${{ runner.os }}-invoices-app
            
      - name: Install dependencies
        run: npm install

      - name: Build
        env: 
            GATSBY_API_BASE_URL: ${{ secrets.GATSBY_API_BASE_URL }}
        run: npm run build
        
      - name: Set AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: sa-east-1
          
      - name: Deploy to S3
        run: npm run deploy

  dockerize:
    runs-on: ubuntu-latest
    needs: build
    steps:
    
      - name: Check Out Repo 
        uses: actions/checkout@v2
      
      - name: Set output
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        env:
          RELEASE_VERSION: ${{ steps.vars.outputs.tag }}
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/invoices-app-front:${{ env.RELEASE_VERSION }}, ${{ secrets.DOCKER_HUB_USERNAME }}/invoices-app-front:latest
          build-args: GATSBY_API_BASE_URL=${{ secrets.GATSBY_API_BASE_URL }}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}