name: Deploy App

on:
  push:
    tags:
      - "*"
  
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Caching Gatsby
        id: gatsby-cache-build
        uses: actions/cache@v2
        with:
          path: |
            public
            .cache
            node_modules
          key: ${{ runner.os }}-invoices-app-${{ github.run_id }}
          restore-keys: |
            ${{ runner.os }}-invoices-app
            
      - name: Install dependencies
        run: npm install

      - name: Build
        env: 
            GATSBY_API_BASE_URL: ${{ secrets.GATSBY_API_BASE_URL }}
        run: npm run build
        
      - name: Set AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: sa-east-1
          
      - name: Deploy to S3
        run: npm run deploy